[package]
name = "tokio-timeout"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
timeout-macro-parse = { workspace = true }

[dev-dependencies]
anyhow = "1.0.98"
tokio = { version = "1.45.1", features = ["time", "macros", "rt"] }
