[package]
name = "timeout-macro-parse"
version = "0.1.0"
edition = "2021"

[features]
default = []
test = ["dep:proc-macro2"]

[dependencies]
proc-macro2 = { version = "1.0.95", optional = true }

[dev-dependencies]
criterion = "0.6.0"

[[bench]]
name = "benchmark"
harness = false