name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # 17:30 every day
    - cron: 30 17 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.github.ref }}
  cancel-in-progress: true

jobs:
  format:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-22.04-arm
          - ubuntu-24.04-arm
          - windows-2022
          - windows-2025
          - windows-11-arm
          - macos-13
          - macos-14
          - macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.70.0"
          components: rustfmt
      - name: check formatting
        shell: bash
        run: |
          cargo fmt --all --check

  lint:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-22.04-arm
          - ubuntu-24.04-arm
          - windows-2022
          - windows-2025
          - windows-11-arm
          - macos-13
          - macos-14
          - macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.70.0"
          components: clippy
      - name: clippy
        shell: bash
        run: |
          cargo clippy -- -D warnings
          cargo clippy --tests --features test -- -D warnings

  build:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-22.04-arm
          - ubuntu-24.04-arm
          - windows-2022
          - windows-2025
          - windows-11-arm
          - macos-13
          - macos-14
          - macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.70.0"
      - name: build
        shell: bash
        run: |
          cargo build

  test:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-22.04-arm
          - ubuntu-24.04-arm
          - windows-2022
          - windows-2025
          - windows-11-arm
          - macos-13
          - macos-14
          - macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.70.0"
      - name: test
        shell: bash
        run: |
          cargo test
