on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.70.0"
          components: rustfmt
      - name: check formatting
        shell: bash
        run: |
          cargo fmt --all --check
  lint:
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.70.0"
          components: clippy
      - name: clippy
        shell: bash
        run: |
          cargo clippy
          cargo clippy --tests --features test
  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.70.0"
      - name: build
        shell: bash
        run: |
          cargo build
  test:
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.70.0"
      - name: test
        shell: bash
        run: |
          cargo test
